name: build

on:
  push:
    branches: [ 0.05 ]
  pull_request:
    branches: [ 0.05 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: change_directory_first
      run: cd ..
    - name: change_directory_second
      run: cd ..
    - name: chmod shell files
      run: chmod +x config.sh
    - name: configure
      run: ./config.sh
    - name: change to kernel directory
      run: cd kernel
    - name: make kernel
      run: make
    - name: check directory
      run: pwd
    - name: change to libc directory
      run: ../libc/
    - name: make check
      run: make check
    - name: make image
      run: make image
