name: build

on:
  push:
    branches: [ 0.06 ]
  pull_request:
    branches: [ 0.06 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Make the shell files executable
      run: chmod +x scripts/*.sh
      
    - name: Configure
      run: cd scripts/ && ./config.sh
